#??????id
authority.applicationId = 981194468570960001

#??id
role.manager = 986227712144197857
role.courier = 986695985591778017
role.driver = 989188868496427393
role.dispatcher = 996045927523359809

#?? ???OSS
spring.alioss.endpoint = oss-cn-shanghai.aliyuncs.com
spring.alioss.accessKeyId = LTAI4G2g6WqYBZyZMovev1pd
spring.alioss.accessKeySecret = 2Q4x5TpgHRP8Eo3ehQzCJxPteBl4R4
spring.alioss.bucketName = itheima-sh-oss