jdbc.url = jdbc:mysql://192.168.150.101:3306/sl_trade?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
jdbc.username = root
jdbc.password = 123

#redis???
redis.host = 192.168.150.101
redis.port = 6379
redis.password = 123321

#?????
#??????????????
qrcode.margin = 2
#??????????
qrcode.fore-color = #000000
#????????
qrcode.back-color = #ffffff
#?????????????????????????????????????????????????????????????
#??????????L?M?Q?H????M
qrcode.error-correction-level = M
#?
qrcode.width = 300
#?
qrcode.height = 300

#??????????????
job.trading.count = 100
job.refund.count = 100

#xxl-job???
xxl.job.executor.appname=sl-express-ms-trade