#??token
sl.jwt.user-secret-key = sl
sl.jwt.user-ttl = 7200000

#??????
sl.wechat.appid = wx*******
sl.wechat.secret = *****************
#???????id??????
sl.wechat.enterpriseId = 1561414331

#??????????
real-name-registration.enable = false
spring.eidverify.url = https://eid.shumaidata.com/eid/check
spring.eidverify.appCode = xxxxxx